apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: application
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:

  project: default

  source:
    repoURL: https://github.com/itaytzdaka/weather-app.git
    targetRevision: main
    path: gitops/charts/application
    helm:
      valueFiles:
        - values-local.yaml

  destination:
    server: https://kubernetes.default.svc
    namespace: app
    
  syncPolicy:

    syncOptions:
      - CreateNamespace=true

    automated:
      prune: true
      selfHeal: true
