# Dockerfile - Server

# Use Node.js base image
FROM node:18

# Set working directory
WORKDIR /app

# Copy package.json and install dependencies
COPY server/package.json server/package-lock.json .
RUN npm install

# Copy source code
COPY /server .

# Expose port
EXPOSE 3000

# Start server
CMD ["npm", "start"]

