services:

  node:
    build:
      context: .
      dockerfile: Dockerfile.node
    container_name: node
    ports:
      - "3000:3000"
    networks:
      - weather-network

  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
      args:
        - REACT_APP_API_URL=/
    environment:
      - SERVER=node
      - PORT=3000
    container_name: nginx
    ports:
      - "80:80"
    depends_on:
      - node
    networks:
      - weather-network

networks:
  weather-network:

