apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ingress-nginx
  namespace: argocd
  annotations:
      argocd.argoproj.io/sync-wave: "2"
spec:

  project: default

  source:
    repoURL: git@gitlab.com:itay-protfolio/gitops.git
    targetRevision: main
    path: charts/ingress-nginx
    # helm:
    #   valueFiles:
    #     - values.yaml
    helm:
      parameters:
        # - name: controller.service.type
        #   value: LoadBalancer
        # - name: controller.replicaCount
        #   value: "1"
        # - name: controller.ingressClassResource.name
        #   value: nginx
        # - name: controller.ingressClassResource.enabled
        #   value: "true"
        # - name: controller.admissionWebhooks.enabled
        #   value: "true"
        # - name: controller.admissionWebhooks.patch.enabled
        #   value: "true"
        - name: controller.admissionWebhooks.enabled
          value: "fale"
        # - name: controller.admissionWebhooks.port
        #   value: "8443"
        # - name: controller.admissionWebhooks.service.servicePort
        #   value: "443"
        # - name: controller.admissionWebhooks.service.targetPort
        #   value: "8443"

  destination:
    server: https://kubernetes.default.svc
    namespace: ingress-nginx
    
  syncPolicy:

    syncOptions:
      - CreateNamespace=true

    automated:
      prune: true
      selfHeal: true
