{{- if .Values.clusterIssuer.enabled | default false }}
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: {{ .Values.clusterIssuer.name }}
  # annotations:
  #   "helm.sh/hook": post-install
  #   "helm.sh/hook-delete-policy": before-hook-creation
spec:
  {{- if hasKey .Values.clusterIssuer "acme" }}
  acme:
    server: {{ .Values.clusterIssuer.acme.server }}
    email: {{ .Values.clusterIssuer.acme.email }}
    privateKeySecretRef:
      name: {{ .Values.clusterIssuer.acme.privateKeySecretRef }}
    solvers:
      - http01:
          ingress:
            class: {{ .Values.clusterIssuer.acme.ingressClass }}
  {{- else if .Values.clusterIssuer.selfSigned }}
  selfSigned: {}
  {{- end }}
{{- end }}