apiVersion: apps/v1
kind: Deployment

metadata:
  name: server-deployment
  labels:
    app: server

spec:
  replicas: {{ .Values.server.replicaCount }}

  selector:
    matchLabels:
      app: server

  template:

    metadata:
      labels:
        app: server

    spec:
            
      containers:
        - name: server

          
          image: "{{ .Values.server.image.repository }}:{{ .Values.server.image.tag | default .Chart.AppVersion }}"

          ports:
            - containerPort: {{ .Values.server.service.port }}


          {{- with .Values.server.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}


          {{- with .Values.server.startupProbe }}
          startupProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}

          {{- with .Values.server.readinessProbe }}
          readinessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}

          {{- with .Values.server.livenessProbe }}
          livenessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}