apiVersion: v1
kind: Service

metadata:
  name: weather-server-service
  labels:
    app: weather

spec:
  ports:
    - port: {{ .Values.server.service.port }}
      targetPort: {{ .Values.server.service.port }}
  selector:
    app: server