apiVersion: v1
kind: Service

metadata:
  name: todos-client-service
  labels:
    app: todos

spec:
  ports:
    - port: {{ .Values.client.service.port }}
      targetPort: {{ .Values.client.service.port }}
  selector:
    app: client